language: go

go:
  - 1.4.1
  - tip

install:
  - go get -v github.com/golang/lint/golint
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v golang.org/x/tools/cmd/vet
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v -u github.com/kr/godep
  - godep get
  - godep go build -v ./...
script:
  - godep go test ./...
  - test -z "$(go fmt ./...)"
  - go vet .
  - $HOME/gopath/bin/golint .
  - go test -cpu=2 -covermode=atomic ./...
